FROM ubuntu:16.04

RUN apt-get update && \
	apt-get install -y \
		curl \
		libfreetype6 \
		libglu1-mesa \
		libxi6 \
		libxrender1 \
		xz-utils && \
	apt-get -y autoremove

# # install python3.6
# RUN apt-get install -y software-properties-common \
#   && add-apt-repository ppa:deadsnakes/ppa \
#   && apt-get update \
#   && apt-get install -y build-essential python3.6 python3.6-dev python3-pip python3.6-venv
# # update pip
# RUN python3.6 -m pip install pip --upgrade \
#     && python3.6 -m pip install wheel pyyaml


# RUN apt-get install -y python3-dev python3-pip python3-setuptools \
#     && ln -s /usr/bin/python3 /usr/local/bin/python \
#     && /usr/local/bin/python --version
# # RUN easy_install3 pip

# RUN pip install virtualenv
# RUN which python3.6
# RUN python3.6 --version

# RUN python -m pip install PyYAML

# ENV PYTHONPATH /usr/bin/

ENV BLENDER_MAJOR 2.82
ENV BLENDER_VERSION 2.82a
ENV BLENDER_URL https://download.blender.org/release/Blender${BLENDER_MAJOR}/blender-${BLENDER_VERSION}-linux64.tar.xz

RUN curl -L ${BLENDER_URL} | tar -xJ -C /usr/local/ 
RUN mv /usr/local/blender-${BLENDER_VERSION}-linux64 /usr/local/blender
    # && mv /usr/local/blender/2.82/python /usr/local/blender/2.82/__python 
    
# run the pip install for the bundled python
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN /usr/local/blender/${BLENDER_MAJOR}/python/bin/python3.7m get-pip.py

# RUN ls -fal /usr/local/blender/${BLENDER_MAJOR}/python/bin/python3.7m
RUN /usr/local/blender/${BLENDER_MAJOR}/python/bin/python3.7m -m pip install pyyaml

# RUN ls -fal /usr/local/blender/${BLENDER_MAJOR}/python/lib/python3.7/

# RUN /usr/local/blender/${BLENDER_MAJOR}/python/bin/python3.7m /usr/local/blender/${BLENDER_MAJOR}/python/local/lib/python3.5/dist-packages/pip install pyyaml

VOLUME /media
WORKDIR /
ENTRYPOINT ["/usr/local/blender/blender", "-b"]