name: Release
on:
  workflow_dispatch: # manually only for now

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Contents into Folder
      run: zip -r release.zip blender/*.blend blender/models/*.obj docs/ scripts/* config.yaml Makefile .gitignore LICENSE README.md
      
    - name: Bump version and Push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}