name: Full Render

on:
  push:
    branches: [ main ]

  # allows for manual triggering from github
  workflow_dispatch:

jobs:
  Scene-Render:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Create Raw Render from Scene
        run: |
          echo "Creating inital buffer frames"
          # make scene_render
          scripts/render.py --stage=scene

      - name: Upload Buffer Images as Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: scene-buffer-files
          path: imgs/buffer/

  Final-Render:
    needs: Scene-Render
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Create Composite Render
        run: |
          echo "Creating composited avi"
          # make edit_render
          scripts/render.py --stage=edit

      - name: Upload Completed Movie
        uses: actions/upload-artifact@v1
        with:
          name: output-render-file
          path: |
            imgs/out/
            imgs/buffer/